--ALTER session set "_oracle_script"=true;
--CREATE USER RELACION3 IDENTIFIED BY RELACION3;
--GRANT CONNECT, RESOURCE, DBA TO RELACION3;

CREATE TABLE LECTORES(
	COD_LE NUMBER(6) PRIMARY KEY,
	APELLIDOS_LE VARCHAR2(30),
	NOMBRE_LE VARCHAR2(15),
	TIPO_LE CHAR(10) NOT NULL,
	SEXO_LE CHAR(1) NOT NULL CHECK (SEXO_LE IN('H','M')),
	MOROSO_LE DATE DEFAULT NULL,
	-- Fecha de levantamiento de la sanción
	SANCIONES_LE NUMBER(2)
	-- Nº de sanciones hasta la fecha
);

CREATE TABLE AUTORES(
	COD_AU NUMBER(6) PRIMARY KEY,
	NOMBRE_AU VARCHAR2(30)
);

CREATE TABLE EDITORIALES(
	COD_ED NUMBER(6) PRIMARY KEY,
	NOMBRE_ED VARCHAR2(30)
);

CREATE TABLE LIBROS(
	COD_LI NUMBER(6) PRIMARY KEY,
	AUTOR_LI NUMBER(6) REFERENCES AUTORES,
	TITULO_LI VARCHAR2(50),
	EDITORIAL_LI NUMBER(6) REFERENCES EDITORIALES,
	ESTADO_LI NUMBER(2),
	PRESTADO_LI CHAR(1) DEFAULT ('N')
);

CREATE TABLE PRESTAMOS(
	CODLEC_PR NUMBER(6) REFERENCES LECTORES,
	CODLIB_PR NUMBER(6) REFERENCES LIBROS,
	FECHA_PR DATE DEFAULT SYSDATE,
	DEVOL_PR DATE DEFAULT NULL, -- Fecha de devolución
	PRIMARY KEY ( CODLEC_PR, CODLIB_PR, FECHA_PR),
	CONSTRAINT CH_FECHA CHECK (DEVOL_PR > FECHA_PR)
);

